<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Statistical Analysis</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<link href="site_libs/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-5.3.1/bootstrap.bundle.min.js"></script>
<script src="site_libs/bs3compat-0.8.0/transition.js"></script>
<script src="site_libs/bs3compat-0.8.0/tabs.js"></script>
<script src="site_libs/bs3compat-0.8.0/bs3compat.js"></script>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="maps.html">Maps</a>
</li>
<li>
  <a href="exploratory_analysis.html">Exploratory Analysis</a>
</li>
<li>
  <a href="statistical_analysis.html">Statistical Analysis</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="mailto:&lt;kx2224@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/KanyeXuSelf/p8105_FinalProject.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Statistical Analysis</h1>

</div>


<pre class="r"><code>library(rvest)
library(dplyr)
library(tidyverse)
library(httr)
library(ggplot2)
library(tidyr)
library(maps)
library(knitr)
library(viridis)
library(broom)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 8,      
  fig.asp = 0.6,     
  out.width = &quot;80%&quot;   
)


theme_set(theme_minimal() + theme(legend.position = &quot;right&quot;))

options(
  ggplot2.continuous.colour = &quot;viridis&quot;,
  ggplot2.continuous.fill = &quot;viridis&quot;
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

rm(list = ls())

country_overall &lt;- read.csv(&quot;data/country_overall.csv&quot;)
esports_top100 &lt;- read.csv(&quot;data/esports_earnings_top100_overall.csv&quot;)
top500_365 &lt;- read.csv(&quot;data/top500_365.csv&quot;)
earnings_country &lt;- read.csv(&quot;data/Earnings_country_2018_2024.csv&quot;)
earnings_topgame &lt;- read.csv(&quot;data/Earnings_topgame_2018_2024.csv&quot;)

country_overall$Total_Earnings &lt;- as.numeric(gsub(&quot;[\\$,]&quot;, &quot;&quot;, country_overall$Total_Earnings))
esports_top100$Total_Earnings &lt;- as.numeric(gsub(&quot;[\\$,]&quot;, &quot;&quot;, esports_top100$Total_Earnings))
top500_365$`Total..Last.365.Days.` &lt;- as.numeric(gsub(&quot;[\\$,]&quot;, &quot;&quot;, top500_365$`Total..Last.365.Days.`))
earnings_country$Overall_Earnings &lt;- as.numeric(gsub(&quot;[\\$,]&quot;, &quot;&quot;, earnings_country$Overall_Earnings))
earnings_topgame$Total_Earnings &lt;- as.numeric(gsub(&quot;[\\$,]&quot;, &quot;&quot;, earnings_topgame$Total_Earnings))</code></pre>
<p>In this section, we conduct statistical modeling and analysis to
investigate factors influencing total earnings in esports games. The
analysis begins with t-tests to examine differences in earnings across
countries over multiple years, assessing whether the industry
demonstrated resilience during the COVID-19 pandemic by rebounding after
a significant decline in 2020. This is followed by linear regression
with interaction terms, residual diagnostics, and prediction
visualization to further explore the factors impacting total
earnings.</p>
<div id="data-cleaning-and-feature-engineering-for-t-test"
class="section level2">
<h2>1.1 Data Cleaning and Feature Engineering for t-test</h2>
<p>We consolidate earnings data across four years (2018, 2019, 2020, and
2021) by performing an iterative inner join on the Countries column.
Each year’s data is first filtered, renamed for clarity
(Earnings_<Year>), and included in the merge process. The resulting
dataset aligns earnings for the same countries across all years,
ensuring only countries present in all four years are included. This
cleaned and structured data enables paired comparisons and
year-over-year analysis.</p>
<pre class="r"><code>paired_data &lt;- reduce(
  list(
    earnings_country %&gt;% filter(Year == 2018) %&gt;% select(Countries, Earnings_2018 = Overall_Earnings),
    earnings_country %&gt;% filter(Year == 2019) %&gt;% select(Countries, Earnings_2019 = Overall_Earnings),
    earnings_country %&gt;% filter(Year == 2020) %&gt;% select(Countries, Earnings_2020 = Overall_Earnings),
    earnings_country %&gt;% filter(Year == 2021) %&gt;% select(Countries, Earnings_2021 = Overall_Earnings)
  ),
  inner_join,
  by = &quot;Countries&quot;
)</code></pre>
</div>
<div id="paired-t-tests" class="section level2">
<h2>1.2 Paired T-Tests</h2>
<p>Null Hypothesis (H₀): There is no significant difference in esports
earnings between 2018 (pre-pandemic) and 2019 (pandemic onset).
Alternative Hypothesis (H₁): Esports earnings in 2018 are significantly
different from 2019, reflecting the impact of the pandemic.</p>
<p>Null Hypothesis (H₀): There is no significant difference in esports
earnings between 2019 (pandemic onset) and 2020 (initial pandemic
impact). Alternative Hypothesis (H₁): Esports earnings in 2019 are
significantly different from 2020, reflecting the industry’s resilience
or adaptation during the initial pandemic year.</p>
<p>Null Hypothesis (H₀): There is no significant difference in esports
earnings between 2020 (pandemic onset) and 2021 (recovery phase).
Alternative Hypothesis (H₁): Esports earnings in 2021 are significantly
different from 2020, indicating a recovery or continued decline.</p>
<pre class="r"><code># Function for t-tests
perform_t_test &lt;- function(data, col1, col2) {
  t_test &lt;- t.test(data[[col1]], data[[col2]], paired = TRUE)
  tidy_results &lt;- broom::tidy(t_test)
  return(tidy_results)
}

# Apply t-tests to year pairs
t_test_results &lt;- list(
  `2018 vs 2019` = perform_t_test(paired_data, &quot;Earnings_2018&quot;, &quot;Earnings_2019&quot;),
  `2019 vs 2020` = perform_t_test(paired_data, &quot;Earnings_2019&quot;, &quot;Earnings_2020&quot;),
  `2020 vs 2021` = perform_t_test(paired_data, &quot;Earnings_2020&quot;, &quot;Earnings_2021&quot;)
)

# Combine results into a table
combined_results &lt;- purrr::map_dfr(t_test_results, ~., .id = &quot;Year Comparison&quot;)
combined_results %&gt;%
  kable(digits = 5, caption = &quot;Paired T-Test Results for Earnings Between Years&quot;)</code></pre>
<table>
<caption>Paired T-Test Results for Earnings Between Years</caption>
<colgroup>
<col width="15%" />
<col width="9%" />
<col width="9%" />
<col width="7%" />
<col width="9%" />
<col width="10%" />
<col width="9%" />
<col width="13%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Year Comparison</th>
<th align="right">estimate</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2018 vs 2019</td>
<td align="right">-545207.8</td>
<td align="right">-3.36884</td>
<td align="right">0.00104</td>
<td align="right">111</td>
<td align="right">-865901.2</td>
<td align="right">-224514.4</td>
<td align="left">Paired t-test</td>
<td align="left">two.sided</td>
</tr>
<tr class="even">
<td align="left">2019 vs 2020</td>
<td align="right">772820.2</td>
<td align="right">3.54599</td>
<td align="right">0.00057</td>
<td align="right">111</td>
<td align="right">340953.8</td>
<td align="right">1204686.7</td>
<td align="left">Paired t-test</td>
<td align="left">two.sided</td>
</tr>
<tr class="odd">
<td align="left">2020 vs 2021</td>
<td align="right">-984980.7</td>
<td align="right">-3.17808</td>
<td align="right">0.00192</td>
<td align="right">111</td>
<td align="right">-1599126.3</td>
<td align="right">-370835.1</td>
<td align="left">Paired t-test</td>
<td align="left">two.sided</td>
</tr>
</tbody>
</table>
<p>The paired t-test results reveal significant year-over-year changes
in esports earnings between 2018 and 2021. From 2018 to 2019, earnings
increased significantly, with 2019 showing an average increase of
$545,207.8 compared to 2018 (<em>t</em> = -3.37, <em>p</em> = 0.00104).
During the initial year of the COVID-19 pandemic (2019 to 2020),
earnings surged by an average of $772,820.2 (<em>t</em> = 3.55,
<em>p</em> = 0.00057), highlighting the industry’s resilience, likely
driven by a shift to online platforms and increased viewership during
global lockdowns. However, from 2020 to 2021, earnings declined
significantly by $984,980.7 on average (<em>t</em> = -3.18, <em>p</em> =
0.00192), suggesting potential challenges in sustaining growth as the
pandemic subsided and market dynamics normalized. These findings
demonstrate the esports industry’s adaptability during the pandemic but
also highlight the importance of addressing post-pandemic challenges to
ensure continued growth.</p>
<pre class="r"><code># Pivot the paired_data to a long format
long_data &lt;- paired_data %&gt;%
  pivot_longer(
    cols = starts_with(&quot;Earnings_&quot;),
    names_to = &quot;Year&quot;,
    values_to = &quot;Earnings&quot;
  ) %&gt;%
  mutate(
    Year = case_when(
      Year == &quot;Earnings_2018&quot; ~ &quot;2018&quot;,
      Year == &quot;Earnings_2019&quot; ~ &quot;2019&quot;,
      Year == &quot;Earnings_2020&quot; ~ &quot;2020&quot;,
      Year == &quot;Earnings_2021&quot; ~ &quot;2021&quot;
    )
  )

# Create an interactive boxplot using plotly
plot_ly(
  data = long_data,
  x = ~Year,
  y = ~Earnings,
  type = &quot;box&quot;,
  boxpoints = &quot;all&quot;, # Include all points (jittered)
  jitter = 0.3,
  pointpos = -1.8,
  marker = list(color = &quot;skyblue&quot;, opacity = 0.6)
) %&gt;%
  layout(
    title = &quot;Distribution of Esports Earnings by Year&quot;,
    xaxis = list(title = &quot;Year&quot;),
    yaxis = list(
      title = &quot;Earnings&quot;,
      tickvals = seq(0, 100000, by = 20000), # Set y-axis ticks
      tickformat = &quot;,.0f&quot; # Format ticks as integers
    )
  )</code></pre>
<div class="plotly html-widget html-fill-item" id="htmlwidget-e52f1fa7c62d24a51c68" style="width:80%;height:460.8px;"></div>
<script type="application/json" data-for="htmlwidget-e52f1fa7c62d24a51c68">{"x":{"visdat":{"39903fb11536":["function () ","plotlyVisDat"]},"cur_data":"39903fb11536","attrs":{"39903fb11536":{"x":{},"y":{},"boxpoints":"all","jitter":0.29999999999999999,"pointpos":-1.8,"marker":{"color":"skyblue","opacity":0.59999999999999998},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"box"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Distribution of Esports Earnings by Year","xaxis":{"domain":[0,1],"automargin":true,"title":"Year","type":"category","categoryorder":"array","categoryarray":["2018","2019","2020","2021"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"Earnings","tickvals":[0,20000,40000,60000,80000,100000],"tickformat":",.0f"},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"fillcolor":"rgba(31,119,180,0.5)","x":["2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021","2018","2019","2020","2021"],"y":[30759242.289999999,46485324.969999999,26452336.32,32652546.859999999,22842722.32,24862306.390000001,24556181.420000002,51549194.380000003,14525776.109999999,17397423.940000001,11268704.85,13613730.92,10617906.4,9858449.9499999993,4449652.1399999997,5685027.8899999997,7588236.1900000004,9981949.0299999993,1886056.0800000001,2713187.48,6506818.2599999998,10709398.98,5734854.6600000001,6190625.8499999996,6505555.9000000004,7073564.1900000004,2936520.3999999999,3743532.3900000001,6343270.1200000001,5653624.4699999997,4862810.8200000003,22991593,5366853.2400000002,8237265.9699999997,4121240.8599999999,5471967.8300000001,4553609.6299999999,6230524.46,4492647.8499999996,4977960.9299999997,4248986.71,6916060.4100000001,2586258.2400000002,3254880.79,3753131.4700000002,6374129.7699999996,6061668.29,10669486.529999999,3312451.1000000001,7229564.0800000001,5055561.8499999996,6878354.29,3107179.8700000001,3066070.5899999999,2005856.8999999999,3588200.98,2859578.3300000001,3666316.79,3110910.2999999998,10210935.5,2656585.1099999999,1391638.29,1334784.3600000001,10483019.289999999,2482681.23,2486373.5299999998,1039791.63,3745581.7799999998,2161686.3500000001,3006507.0600000001,1949947.96,2521895.6000000001,1998360.24,2556184.4100000001,3281614.54,5183282.5300000003,1972416.4099999999,3248916.29,1492600.3200000001,1481778.02,1685755.98,3454042.1099999999,963981.65000000002,3449444.75,1385781.4399999999,2301167.5800000001,634018.56000000006,781688.12,1330935.22,784902.80000000005,906228.40000000002,2424523.3599999999,1145049.27,1755236.25,438885.71000000002,970068.35999999999,1122846,3602053.79,1425163.3400000001,1288460.1599999999,1096435.49,1954474.6200000001,1594992.8899999999,2407836.9900000002,1018137.5699999999,727147.80000000005,286586.16999999998,526181.67000000004,963465.76000000001,1473678.6000000001,1606562.1699999999,2865774.9300000002,912605.62,26845.970000000001,113063.42999999999,164782.23000000001,896217.06999999995,638113.55000000005,148210.72,635320.25,886351.05000000005,1065164.96,506483.35999999999,545231.48999999999,880415.93000000005,2108230.46,2684872.1699999999,3917845.96,790281.26000000001,753886.97999999998,590793.71999999997,3008235.8100000001,779385.52000000002,603216.23999999999,652556.58999999997,1157361.6399999999,715483.88,513983.21999999997,688989.55000000005,1195983.76,687358.23999999999,1008902.87,460821.33000000002,876235.58999999997,680790.55000000005,1168118.5800000001,146134.97,230220.10999999999,556113.88,1226910.52,859958.65000000002,1159906.01,506836.56,937407.25,305428.75,483918.44,504262.78000000003,861141.23999999999,971338.05000000005,1662615.5900000001,490821.82000000001,410407.71999999997,227469.69,289526.41999999998,427931.41999999998,2228729.79,879692.14000000001,1785577.22,390571.91999999998,1614108.8799999999,354932.53999999998,372674.90999999997,381054.48999999999,526841.80000000005,529454.85999999999,1006701.59,348432.72999999998,232950.70000000001,229634.88,251780.26999999999,347478.40999999997,217996.22,210702.53,177516.47,307038.5,505548.42999999999,329751.53000000003,611148.19999999995,289198.57000000001,290043.47999999998,199996.13,404255.51000000001,273107.56,363173.02000000002,147774.42000000001,186514.38,270752.42999999999,771751.75,278383.39000000001,222686.84,265951.26000000001,484187.53999999998,543619.01000000001,633456.31999999995,261456.73999999999,121658.21000000001,126482.49000000001,271713.40000000002,255275.75,2819763.0600000001,453225.35999999999,437981.63,237885.09,1063526.3100000001,296514.35999999999,361325.13,232758.45000000001,248754.98999999999,168711.48000000001,322900.91999999998,225604.76999999999,260362.38,265178.28000000003,272805.09999999998,213011.14999999999,268226.47999999998,309080.5,682789.07999999996,202527.19,993038.28000000003,333631.76000000001,1423587.8799999999,185668.29000000001,232037.89999999999,164019.92999999999,174032.54999999999,172189.85000000001,180421.62,71674.419999999998,26576.439999999999,159496.41,474904.51000000001,476015.73999999999,669759.28000000003,155351.79999999999,193101.48999999999,286466.42999999999,605816.18999999994,144575.13,823434.18999999994,597484.18999999994,855036.30000000005,119304.50999999999,2400,900,225,99811.059999999998,60087.93,103684.62,289963.46000000002,84988.559999999998,60324.870000000003,36040.68,76790.410000000003,69672.839999999997,131597.67000000001,36326.550000000003,58954.470000000001,64777.790000000001,13143.1,98127.979999999996,429854.53999999998,61445.120000000003,85233.410000000003,326763.31,129977.83,54299.989999999998,274785.79999999999,94000.679999999993,58225.769999999997,53229.739999999998,38526.339999999997,7898.6199999999999,10863.92,49346.160000000003,150616.17000000001,36350.599999999999,39676.040000000001,47936.18,65371.080000000002,165456.48999999999,632934,47050.970000000001,74134.779999999999,27260,17754.16,41266.959999999999,79749.080000000002,32679.84,284097.89000000001,38889.5,86455.130000000005,3093,16426.200000000001,38702.089999999997,29611.09,29379.77,193478.98000000001,36767.839999999997,115608.87,88494.940000000002,159191.63,35762.5,115936.88,117182.21000000001,358012.59000000003,32998.349999999999,45402.330000000002,115494.32000000001,78231.580000000002,31585,1338.51,3544.6700000000001,4740,28649.290000000001,38572.690000000002,110019.56,213521.01000000001,26318.5,12193.370000000001,30333.389999999999,70242.110000000001,23742.98,40123.480000000003,40986.599999999999,25483.279999999999,19249.310000000001,50973.349999999999,45409.209999999999,99522.729999999996,15794.49,88899.199999999997,52502.260000000002,363977.72999999998,11593.33,10249.84,17473.709999999999,84283.550000000003,7460.4399999999996,207351.82999999999,31853.07,208571,7430.5900000000001,103733.92999999999,159810.66,179835.92999999999,7305.6599999999999,11299.610000000001,21935.279999999999,30849.869999999999,7035.21,32767.619999999999,45631.050000000003,227770.32000000001,5867.8199999999997,14879.49,66646,67831.460000000006,5810.2600000000002,38854.080000000002,45455.599999999999,134139.04000000001,5596.5,32656.740000000002,140144.94,97312.639999999999,5358.8199999999997,69429.699999999997,37529.239999999998,292451.84000000003,4542.5299999999997,37149.720000000001,14002.42,19032.07,4217.3299999999999,2742.3600000000001,22131.389999999999,25620.450000000001,3802.8800000000001,7563.8299999999999,15240.860000000001,31743.740000000002,3799.8800000000001,22885.099999999999,52550.269999999997,79585.899999999994,3753.3299999999999,13719.92,21692.5,33578.720000000001,3333.3299999999999,60,120,138.75999999999999,3000,74245.600000000006,36000,18931.779999999999,2250,37136.779999999999,4500,108008.03999999999,2091.5599999999999,28138.869999999999,29086.57,23027.830000000002,1841.8299999999999,41016.849999999999,43260.529999999999,108255.39,1346.55,37459.639999999999,30837.009999999998,33311.059999999998,600,200,73719.160000000003,106636.47,570.27999999999997,11897.26,8612.2600000000002,31303.040000000001,543.38,72,1698.26,1712.05,285.13999999999999,210,3500,10059.07,113,450,1.1699999999999999,8500,54.939999999999998,11720.030000000001,3971.1500000000001,12918.67],"boxpoints":"all","jitter":0.29999999999999999,"pointpos":-1.8,"marker":{"color":"skyblue","opacity":0.59999999999999998,"line":{"color":"rgba(31,119,180,1)"}},"type":"box","line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>The boxplot and paired t-test results reveal key insights into the
year-over-year changes in esports earnings between 2018 and 2021. Below
are the main observations and interpretations:</p>
<div id="earnings-distribution-not-symmetric" class="section level4">
<h4><strong>1. Earnings Distribution: Not Symmetric</strong></h4>
<ul>
<li>The boxplot indicates that earnings distributions for all years are
<strong>not symmetric</strong>.</li>
<li>Extreme outliers above the boxplots highlight that a few countries
or organizations have disproportionately higher earnings compared to the
majority.</li>
<li>This asymmetry suggests a <strong>skewed distribution</strong>,
where most countries earn relatively low amounts, while a small number
achieve exceptionally high earnings.</li>
</ul>
</div>
<div id="mean-vs.-median" class="section level4">
<h4><strong>2. Mean vs. Median</strong></h4>
<ul>
<li>For all years, the <strong>mean</strong> is likely higher than the
<strong>median</strong>, as shown by the longer whiskers and outliers
above the box.</li>
<li>The paired t-tests measure the differences in <strong>mean
earnings</strong>, which are heavily influenced by these extreme
outliers, even though the median earnings may not change as
significantly between years.</li>
</ul>
</div>
<div id="year-to-year-changes" class="section level4">
<h4><strong>3. Year-to-Year Changes</strong></h4>
<p>The paired t-tests provide additional insights into the changes in
mean earnings: - <strong>2018 vs. 2019</strong>: - Earnings
significantly increased (<span
class="math inline">\(-545,207.8\)</span>, <em>p = 0.00104</em>),
reflecting growth in the esports industry. However, the median earnings
remained closer to the lower range, indicating that the increase was
primarily driven by top performers. - <strong>2019 vs. 2020</strong>: -
Earnings surged dramatically (<span
class="math inline">\(772,820.2\)</span>, <em>p = 0.00057</em>), likely
due to the esports industry’s rapid adaptation to the COVID-19 pandemic.
Online tournaments and increased viewership boosted top performers,
while smaller contributors saw little or no growth. - <strong>2020
vs. 2021</strong>: - Earnings significantly dropped (<span
class="math inline">\(-984,980.7\)</span>, <em>p = 0.00192</em>), likely
reflecting a normalization in the industry as the pandemic-driven surge
faded, and attention shifted back to traditional sports and events.</p>
</div>
</div>
<div id="data-cleaning-and-feature-engineering-for-regression"
class="section level2">
<h2>2.1 Data Cleaning and Feature Engineering for regression</h2>
<p>We clean the data by removing special characters, converting
variables to numeric types, and creating additional features such as
game frequency and encoded year.Frequency Represents the number of times
each game appears in the dataset across years.</p>
<pre class="r"><code># Clean and process `Game` data
data &lt;- earnings_topgame %&gt;%
  mutate(
    Total_Earnings = as.numeric(gsub(&quot;[^0-9.]&quot;, &quot;&quot;, Total_Earnings)),
    Total_Players = as.numeric(gsub(&quot;[^0-9]&quot;, &quot;&quot;, Total_Players)),
    Total_Tournaments = as.numeric(gsub(&quot;[^0-9]&quot;, &quot;&quot;, Total_Tournaments))
  ) %&gt;%
  drop_na()  # Remove rows with missing values

# Count occurrences of each game
game_counts &lt;- data %&gt;%
  count(Game, name = &quot;Frequency&quot;)

# Ensure both objects are data frames
data &lt;- as.data.frame(data)
game_counts &lt;- as.data.frame(game_counts)

# Perform a safe join
data &lt;- left_join(data, game_counts, by = &quot;Game&quot;)

# Add a numerical encoding for Year
data &lt;- data %&gt;%
  mutate(Year = as.numeric(as.factor(Year)))</code></pre>
</div>
<div id="model-fitting-with-interaction-terms" class="section level2">
<h2>2.2 Model Fitting with Interaction Terms</h2>
<p>We conducted a linear regression analysis to model
<code>log(Total_Earnings)</code> based on the following predictors:
<code>Year</code>, <code>Total_Players</code>,
<code>Total_Tournaments</code>, <code>Frequency</code>, and an
interaction term (<code>Total_Players:Total_Tournaments</code>). Below
is a summary of the key findings.</p>
<pre class="r"><code>data &lt;- data %&gt;%
  mutate(Total_Earnings = ifelse(Total_Earnings &lt;= 0, 1, Total_Earnings))

data |&gt; 
  lm(log(Total_Earnings) ~ Year + Total_Players * Total_Tournaments + Frequency, data = _) |&gt; 
  broom::tidy() |&gt; 
  knitr::kable(digits = 5)</code></pre>
<table style="width:100%;">
<colgroup>
<col width="46%" />
<col width="13%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">7.06984</td>
<td align="right">0.22269</td>
<td align="right">31.74729</td>
<td align="right">0.00000</td>
</tr>
<tr class="even">
<td align="left">Year</td>
<td align="right">0.13116</td>
<td align="right">0.04362</td>
<td align="right">3.00722</td>
<td align="right">0.00269</td>
</tr>
<tr class="odd">
<td align="left">Total_Players</td>
<td align="right">0.00515</td>
<td align="right">0.00032</td>
<td align="right">16.12860</td>
<td align="right">0.00000</td>
</tr>
<tr class="even">
<td align="left">Total_Tournaments</td>
<td align="right">0.01188</td>
<td align="right">0.00163</td>
<td align="right">7.27727</td>
<td align="right">0.00000</td>
</tr>
<tr class="odd">
<td align="left">Frequency</td>
<td align="right">0.35930</td>
<td align="right">0.03911</td>
<td align="right">9.18629</td>
<td align="right">0.00000</td>
</tr>
<tr class="even">
<td align="left">Total_Players:Total_Tournaments</td>
<td align="right">-0.00001</td>
<td align="right">0.00000</td>
<td align="right">-12.03882</td>
<td align="right">0.00000</td>
</tr>
</tbody>
</table>
<pre class="r"><code>model_interaction &lt;- lm(log(Total_Earnings) ~ Year + Total_Players * Total_Tournaments + Frequency, data = data)
summary(model_interaction)</code></pre>
<pre><code>## 
## Call:
## lm(formula = log(Total_Earnings) ~ Year + Total_Players * Total_Tournaments + 
##     Frequency, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.3667 -2.1928  0.0397  2.1298  9.9448 
## 
## Coefficients:
##                                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      7.070e+00  2.227e-01  31.747  &lt; 2e-16 ***
## Year                             1.312e-01  4.362e-02   3.007  0.00269 ** 
## Total_Players                    5.152e-03  3.194e-04  16.129  &lt; 2e-16 ***
## Total_Tournaments                1.188e-02  1.633e-03   7.277 6.16e-13 ***
## Frequency                        3.593e-01  3.911e-02   9.186  &lt; 2e-16 ***
## Total_Players:Total_Tournaments -8.054e-06  6.690e-07 -12.039  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.724 on 1194 degrees of freedom
## Multiple R-squared:  0.4207, Adjusted R-squared:  0.4183 
## F-statistic: 173.4 on 5 and 1194 DF,  p-value: &lt; 2.2e-16</code></pre>
<div id="model-interpretation" class="section level4">
<h4>Model interpretation:</h4>
<p>All predictors, including the interaction term, are statistically
significant (p&lt;0.05). Total_Players, Total_Tournaments, and Frequency
show particularly strong effects. The adjusted R-square value is
approximately 0.42, indicating that the model explains 42% of the
variation in log(Total_Earnings).</p>
</div>
</div>
<div id="model-diagnosis" class="section level2">
<h2>2.3 Model diagnosis</h2>
<pre class="r"><code># Residual plots
par(mfrow = c(1, 2))  # Arrange plots in a 1x2 grid

# Residuals vs Fitted
plot(model_interaction, which = 1, main = &quot;Residuals vs Fitted&quot;)

# Normal Q-Q plot
plot(model_interaction, which = 2, main = &quot;Normal Q-Q Plot&quot;)</code></pre>
<p><img src="statistical_analysis_files/figure-html/unnamed-chunk-8-1.png" width="80%" /></p>
<p>The model provides significant insights into the predictors of
esports earnings, with key variables such as Total_Players,
Total_Tournaments, and Frequency showing strong effects. However,
diagnostic plots reveal potential issues:</p>
<p>Non-linearity and Heteroscedasticity: Residuals suggest the model may
not fully capture the relationship between predictors and earnings,
especially for extreme values. Outliers: Points like 219, 299, and 824
significantly deviate, indicating the need for robust methods or further
investigation. Normality: While most residuals align with normality,
tail deviations highlight areas for improvement.</p>
<p>To refine the model, feature engineering, non-linear terms, and
robust methods could enhance predictive performance and better handle
anomalies.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
